//---------------------------------------------
package main

//---------------------------------------------
import (
	AST "go/ast"
	FORMAT "go/format"
	PARSER "go/parser"
	TOKEN "go/token"
	LOG "log"
	OS "os"
	TEMPLATE "text/template"
	UNICODE "unicode"
)

//---------------------------------------------
const (
	raw = "Services/Services.go"
)

//---------------------------------------------
func main() {
	if len(OS.Args) <= 1 {
		return
	}

	// parser
	fset := TOKEN.NewFileSet()
	f, err := PARSER.ParseFile(fset, raw, nil, 0)
	if err != nil {
		LOG.Fatal(err)
	}

	// remove Init()
LOOP:
	for k := range f.Decls {
		switch f.Decls[k].(type) {
		case *AST.FuncDecl:
			decl := f.Decls[k].(*AST.FuncDecl)
			if decl.Name.Name == "Init" {
				f.Decls = append(f.Decls[:k], f.Decls[k+1:]...)
				break LOOP
			}
		}
	}

	// create file
	out, err := OS.Create("services.go")
	if err != nil {
		LOG.Fatal(err)
	}

	// rewrite
	FORMAT.Node(out, fset, f)

	//add stub
	funcMap := TEMPLATE.FuncMap{
		"Name": func(s string) string {
			a := []rune(s)
			a[0] = UNICODE.ToUpper(a[0])
			return string(a)
		},
	}
	tmpl, err := TEMPLATE.New("proto.tmpl").Funcs(funcMap).Parse(t)
	if err != nil {
		LOG.Fatal(err)
	}
	err = tmpl.Execute(out, OS.Args[1:])
	if err != nil {
		LOG.Fatal(err)
	}
}

//---------------------------------------------
var t = `
// stubs generated by discover
// DO NOT EDIT!!!
{{range .}}
func Get{{Name .}}WithId(id string) *grpc.ClientConn {
	return _default_pool.get_service_with_id(DEFAULT_SERVICE_PATH + "/{{.}}", id)
}
{{end}}
{{range .}}
func Get{{Name .}}() *grpc.ClientConn {
	return _default_pool.get_service(DEFAULT_SERVICE_PATH + "/{{.}}")
}
{{end}}

func Init() {
	var names []string
	{{range .}}names = append(names, "{{.}}"){{end}}
	_default_pool.init(names...)
}
`
